### ISSUE TITLE
[feat] 앱 잠금화면 설정 뷰 그리기 & 더보기 탭 리팩토링

### ISSUE THREAD

**Issue by snowedev** [TeamCherish/Cherish-iOS#34]
## 💡 Issue
앱 잠금 기능을 위해 설정 부분을 추가합니다.

## 📝 todo
- [x] 더보기 탭 리팩토링
- [x] 더보기 탭에 잠금화면 설정 추가
- [x] 앱 잠금화면 뷰 제작
- [x] 잠금화면 로직
- [x] 잠금화면 뷰 연결
- [x] SceneDelegate 로직 리팩토링
- [x] SceneDelegate 로직 리팩토링하면서 Splash 로직 변경
