### ISSUE TITLE
[bug] 잠금 비활성화시 SceneDelegate 로직에서 뷰 전환 문제, Navi Swipe Gesture app freeze현상

### ISSUE THREAD

**Issue by snowedev** [TeamCherish/Cherish-iOS#37]
## 🐞 버그 설명
스크린 샷, 작동 환경 (OS, device 등)을 적어주세요.

## 📝 todo
- [x] 잠금 없을 때 SceneDelegate 로직에서 뷰 전환 문제
- [x] 회원가입 Flow 네비 바 hidden 안되는 문제
- [x] [Navigation Stack에 뷰가 하나있지만 swipe action이 활성화되어있으면 앱이 freeze되는 현상](https://stackoverflow.com/questions/18946302/uinavigationcontroller-interactive-pop-gesture-not-working)
