### ISSUE TITLE
[refactor] 앱 잠금화면 로직 리팩토링

### ISSUE THREAD

**Issue by snowedev** [TeamCherish/Cherish-iOS#41]
## 💡 Issue
* 현재는 SceneDelegate willConnectTo에 로직을 구현해서 앱 실행중에 한번만 잠금화면이 나옴
* 그래서 앱이 Background에 있다가 InActive->Active 를 거쳐서 진입하려하면 잠금화면 띄우도록 로직 수정
* 또한 앱이 InActive 나 Background 모드 진입시 앱 정보를 가리기 위해 Blur 처리 추가 예정

## 📝 todo
- [x] 그래서 앱이 Background에 있다가 InActive->Active 를 거쳐서 진입하려하면 잠금화면 띄우도록 로직 수정
- [x] 또한 앱이 InActive 나 Background 모드 진입시 앱 정보를 가리기 위해 Blur 처리 추가 예정
- [x] 비밀번호 설정시 비밀번호 확인 로직 반영(빼먹고 안했었음)
