### ISSUE TITLE
[hotfix] TestFlight 1.9(2) 버그 수정

### ISSUE THREAD

**Issue by snowedev** [TeamCherish/Cherish-iOS#49]
## 🐞 버그 설명
1) 식물 물주기 -> 카톡으로 물을 줬을 경우 -> 체리쉬 앱으로 돌아와서 -> 기록 남긴 후 -> 물주기 모션이 블라인드로 처리되어 보여짐

2) 앱 첫 가입 이후 -> 첫 식물 등록 -> 메인 홈으로 진입시 -> 하단 탭바가 보이지 않음
- 단, 앱을 껏다 키면 탭바가 올바르게 생성됨

3) 홈 하단 탭바 영역에 양쪽 사이드에 여백이 생김 -> 아이폰 사용시 폰 화면이 둥그러서 사용상 문제를 못느끼지만 -> 캡처시 하단에 여백이 나타남

4) 미루기 기능에서 현재 날짜 기준으로 미룰 날짜를 계산하여 보여주는데 이 부분의 계산이 잘못되고 있음

## 📝 todo
- [x] 1번 이슈 해결: 연락하기로 넘어갈때 가림막 add 된 뒤에 리뷰하기 뷰가 add돼서 블라인드가 안지워짐
- [x] 2번 이슈 해결: 뷰 맵핑 오류 탭바뷰로 매핑하여 해결
- [x] 3번 이슈 해결: 체리시 서랍이 라운드가 4코너 다 먹혀있어서 2코너만 먹여서 해결
- [x] 4번 이슈 해결: 날짜 계산 로직 개선
