### ISSUE TITLE
[bug] 식물등록 flow 뷰 트랜지션 버그 수정

### ISSUE THREAD

**Issue by snowedev** [TeamCherish/Cherish-iOS#57]
## 🐞 버그 설명
메인뷰의 추가버튼을 제외하고 마이페이지,  검색이후 등록 등에서 이전 수정사항이 반영되지 않은 문제점 발견

## 📝 todo
- [x] 식물이 0개일 때 식물등록 플로우 수정
- [x] 마이페이지 식물등록 플로우 수정
- [x] 검색뷰에서 식물등록 플로우 수정
